# -*- coding: utf-8 -*-
"""ImageClassificationWithCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pgtvicoIZcbQA45yRxeYKs3OZf6PPpy

# Image Classification with Convolutional Neural Networks (CNNs)

##  Project Overview
In this project, we build, train, and evaluate a Convolutional Neural Network (CNN) to automatically classify images into ten distinct categories. Using modern deep learning techniques, this notebook demonstrates the end-to-end workflow of a computer vision project—from raw data ingestion to making predictions on custom, real-world images.

##  The Dataset
We are using the famous **CIFAR-10 dataset**, a standard benchmark in machine learning. It consists of 60,000 color images (32x32 pixels) divided evenly across 10 classes:
*   **Vehicles:** Aeroplane, Automobile, Ship, Truck
*   **Animals:** Bird, Cat, Deer, Dog, Frog, Horse

##  Technology Stack
*   **Environment:** Google Colab (Cloud GPU)
*   **Libraries:** Python, TensorFlow, Keras (Deep Learning), NumPy (Math/Arrays), Matplotlib & Pillow (Image processing and visualization).

##  Project Workflow
1.  **Data Loading & Visualization:** Importing the CIFAR-10 dataset and plotting sample images to understand our data structure.
2.  **Data Preprocessing:**
    *   Normalizing pixel values to a scale of 0.0 to 1.0 to help the neural network converge faster.
    *   Applying one-hot encoding to our target labels.
3.  **Model Architecture:** Constructing a Sequential CNN model utilizing:
    *   `Conv2D` layers to extract spatial features.
    *   `MaxPooling2D` to downsample and reduce computational load.
    *   `Dropout` layers to prevent the model from overfitting to the training data.
    *   Fully connected `Dense` layers to output the final prediction probabilities.
4.  **Training & Evaluation:** Compiling the model with Stochastic Gradient Descent (SGD) and training it over 10 epochs. We then evaluate its accuracy against unseen test data.
5.  **Real-World Inference & Error Analysis:** Loading custom images from the internet, preprocessing them to match our training pipeline, and feeding them to our trained model to see how it performs on both obvious and "tricky" images.

### 1) Loading the dataset
"""

from keras.datasets import cifar10
import matplotlib.pyplot as plt

(train_X,train_Y),(test_X,test_Y)=cifar10.load_data()

"""### 2) Plotting some images for visualisation"""

n=6
plt.figure(figsize=(20,10))
for i in range(n):
  plt.subplot(330+1+i)
  plt.imshow(train_X[i])
  plt.show()

"""### 3) Import the required layers and modules to create our convolution neural net architecture"""

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.constraints import MaxNorm
from keras.optimizers import SGD
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.utils import to_categorical

"""### 4) Convert the pixel values of the dataset to float type and then normalize the dataset"""

train_x=train_X.astype('float32')
test_X=test_X.astype('float32')

train_X=train_X/255.0
test_X=test_X/255.0

"""### 5) Now performing the one-hot encoding for target classes"""

train_Y = to_categorical(train_Y)
test_Y = to_categorical(test_Y)

num_classes = test_Y.shape[1]

"""### 6) Create the sequential model and add the layers"""

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(32, 32, 3),
                 padding='same', activation='relu',
                 kernel_constraint=MaxNorm(3)))

model.add(Dropout(0.2))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same',
                 kernel_constraint=MaxNorm(3)))

model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu', kernel_constraint=MaxNorm(3)))

model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

"""### 7) Configuring the optimizer and compile the model"""

sgd = SGD(learning_rate=0.01, momentum=0.9, nesterov=False)

model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

"""### 8) Viewing the model summary for better understanding of model architecture"""

model.summary()

"""### 9) Training the model"""

model.fit(train_X,train_Y,
    validation_data=(test_X,test_Y),
    epochs=10,batch_size=32)

"""### 10) Calculating its accuracy on testing data"""

_,acc=model.evaluate(test_X,test_Y)
print(acc*100)

"""### 11) Saving the model"""

model.save("model1_cifar_10epoch.h5")

"""### 12) Make a dictionary to map to the output classes and make predictions from the model"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Dictionary of class labels
results = {
   0: 'aeroplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer',
   5: 'dog', 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'
}

image_path = "/Cat_November_2010-1a.jpg"

# 1. Load and process the image for the model
im = Image.open(image_path)
im_resized = im.convert('RGB').resize((32, 32))
im_array = np.array(im_resized)

# Normalize the image
im_array = im_array.astype('float32') / 255.0
im_array = np.expand_dims(im_array, axis=0)

# 2. Predict
predictions = model.predict(im_array)
pred = np.argmax(predictions, axis=-1)[0]

print(f"Class ID: {pred}, Prediction: {results[pred]}")

# 3. Display the original image
plt.figure(figsize=(4, 4))
plt.imshow(im) # We show the original 'im' here so it isn't a blurry 32x32 square!
plt.title(f"AI Prediction: {results[pred].title()}", fontsize=14, fontweight='bold')
plt.axis('off') # This hides the graph axes and numbers
plt.show()

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Dictionary of class labels
results = {
   0: 'aeroplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer',
   5: 'dog', 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'
}

image_path = "/Rusty.jpg"

# 1. Load and process the image for the model
im = Image.open(image_path)
im_resized = im.convert('RGB').resize((32, 32))
im_array = np.array(im_resized)

# Normalize the image
im_array = im_array.astype('float32') / 255.0
im_array = np.expand_dims(im_array, axis=0)

# 2. Predict
predictions = model.predict(im_array)
pred = np.argmax(predictions, axis=-1)[0]

print(f"Class ID: {pred}, Prediction: {results[pred]}")

# 3. Display the original image
plt.figure(figsize=(4, 4))
plt.imshow(im) # We show the original 'im' here so it isn't a blurry 32x32 square!
plt.title(f"AI Prediction: {results[pred].title()}", fontsize=14, fontweight='bold')
plt.axis('off') # This hides the graph axes and numbers
plt.show()

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Dictionary of class labels
results = {
   0: 'aeroplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer',
   5: 'dog', 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'
}

image_path = "/Tarom.b737-700.yr-bgg.arp.jpg"

# 1. Load and process the image for the model
im = Image.open(image_path)
im_resized = im.convert('RGB').resize((32, 32))
im_array = np.array(im_resized)

# Normalize the image
im_array = im_array.astype('float32') / 255.0
im_array = np.expand_dims(im_array, axis=0)

# 2. Predict
predictions = model.predict(im_array)
pred = np.argmax(predictions, axis=-1)[0]

print(f"Class ID: {pred}, Prediction: {results[pred]}")

# 3. Display the original image
plt.figure(figsize=(4, 4))
plt.imshow(im) # We show the original 'im' here so it isn't a blurry 32x32 square!
plt.title(f"AI Prediction: {results[pred].title()}", fontsize=14, fontweight='bold')
plt.axis('off') # This hides the graph axes and numbers
plt.show()

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Dictionary of class labels
results = {
   0: 'aeroplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer',
   5: 'dog', 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'
}

image_path = "/Atelopus_zeteki1.jpg"

# 1. Load and process the image for the model
im = Image.open(image_path)
im_resized = im.convert('RGB').resize((32, 32))
im_array = np.array(im_resized)

# Normalize the image
im_array = im_array.astype('float32') / 255.0
im_array = np.expand_dims(im_array, axis=0)

# 2. Predict
predictions = model.predict(im_array)
pred = np.argmax(predictions, axis=-1)[0]

print(f"Class ID: {pred}, Prediction: {results[pred]}")

# 3. Display the original image
plt.figure(figsize=(4, 4))
plt.imshow(im) # We show the original 'im' here so it isn't a blurry 32x32 square!
plt.title(f"AI Prediction: {results[pred].title()}", fontsize=14, fontweight='bold')
plt.axis('off') # This hides the graph axes and numbers
plt.show()

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Dictionary of class labels
results = {
   0: 'aeroplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer',
   5: 'dog', 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'
}

image_path = "/Nokota_Horses_cropped.jpg"
# 1. Load and process the image for the model
im = Image.open(image_path)
im_resized = im.convert('RGB').resize((32, 32))
im_array = np.array(im_resized)

# Normalize the image
im_array = im_array.astype('float32') / 255.0
im_array = np.expand_dims(im_array, axis=0)

# 2. Predict
predictions = model.predict(im_array)
pred = np.argmax(predictions, axis=-1)[0]

print(f"Class ID: {pred}, Prediction: {results[pred]}")

# 3. Display the original image
plt.figure(figsize=(4, 4))
plt.imshow(im) # We show the original 'im' here so it isn't a blurry 32x32 square!
plt.title(f"AI Prediction: {results[pred].title()}", fontsize=14, fontweight='bold')
plt.axis('off') # This hides the graph axes and numbers
plt.show()

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Dictionary of class labels
results = {
   0: 'aeroplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer',
   5: 'dog', 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'
}

image_path = "/Containerterminal_Altenwerder_(Hamburg-Altenwerder).Iris_Bolten.4.phb.ajb.jpg"
# 1. Load and process the image for the model
im = Image.open(image_path)
im_resized = im.convert('RGB').resize((32, 32))
im_array = np.array(im_resized)

# Normalize the image
im_array = im_array.astype('float32') / 255.0
im_array = np.expand_dims(im_array, axis=0)

# 2. Predict
predictions = model.predict(im_array)
pred = np.argmax(predictions, axis=-1)[0]

print(f"Class ID: {pred}, Prediction: {results[pred]}")

# 3. Display the original image
plt.figure(figsize=(4, 4))
plt.imshow(im) # We show the original 'im' here so it isn't a blurry 32x32 square!
plt.title(f"AI Prediction: {results[pred].title()}", fontsize=14, fontweight='bold')
plt.axis('off') # This hides the graph axes and numbers
plt.show()

"""###  Error Analysis: Why did the AI mistake a Ship for a Frog?

It might seem hilarious that a neural network could confuse a massive metal ship with a tiny green amphibian. However, in the world of computer vision, this mistake actually makes perfect sense! Here is why our model got confused:

*   **The 32x32 Pixel Problem:** The CIFAR-10 dataset squishes every image into a microscopic 32x32 pixel grid. To the AI, it doesn't see sails or lily pads; it just sees blurry blobs of color. A rounded ship hull can easily share the exact same pixel silhouette as a resting frog.
*   **Background & Color Confusion:** Convolutional Neural Networks (CNNs) look for patterns in colors and edges. If the picture features a green or brown ship sitting in blue water, the AI's math might perfectly align with its mathematical definition of a frog (a green/brown blob surrounded by a blue/watery background).
*   **Limited Training (68% Accuracy):** Our model achieved an accuracy of roughly 68% after 10 epochs of training. This means it is statistically expected to get roughly 3 out of every 10 images wrong. It has learned basic features, but it hasn't trained long enough to grasp the deep, complex differences between all 10 classes.

**Takeaway:** This is a perfect example of why **Error Analysis** is a crucial step in Machine Learning. AI doesn't "see" the world with human logic; it only sees patterns of numbers. Understanding *how* it fails helps us design better, deeper models in the future!
"""